 CREATE DATABASE Final;
 
  use Final;

CREATE TABLE CUSTOMER (
IdNo INT NOT NULL AUTO_INCREMENT UNIQUE ,
F_Name CHAR NOT NULL,
L_Name varchar(40) NOT NULL,
Address varchar(40) NOT NULL,
PRIMARY KEY (IdNo)
);

CREATE TABLE PUBLICATION (
PName varchar(100) NOT NULL UNIQUE,
PType varchar(50) NOT NULL,
PRIMARY KEY (PName),
CHECK(PType IN ('Newspaper', 'Magazine'))
);

CREATE TABLE NEWSPAPER (
N_Name varchar(100) NOT NULL UNIQUE,
N_Frequency varchar(10),
PRIMARY KEY (N_Name),
FOREIGN KEY (N_Name) REFERENCES PUBLICATION(PName)
		ON DELETE CASCADE	ON UPDATE CASCADE,
CHECK(N_Frequency IN ('Daily','Weekly')) 
);

CREATE TABLE MAGAZINE (
M_Name varchar(100) NOT NULL UNIQUE,
M_Frequency varchar(10),
PRIMARY KEY (M_Name),
FOREIGN KEY (M_Name) REFERENCES PUBLICATION(PName)
		ON DELETE CASCADE	ON UPDATE CASCADE,
CHECK(M_Frequency IN ('Weekly','Monthly','Quarterly')) 
);

CREATE TABLE DAILY_NEWS_PRICING (
D_Name varchar(100) NOT NULL,
Daily_Rate FLOAT,
No_Of_Days INT NOT NULL,
PRIMARY KEY (D_Name,No_Of_Days),
FOREIGN KEY (D_Name) REFERENCES NEWSPAPER(N_Name)
ON DELETE CASCADE	ON UPDATE CASCADE,
CHECK(No_Of_Days IN (2,5,7)) 
);

CREATE TABLE WEEKLY_NEWS_PRICING (
W_Name varchar(100) NOT NULL,
Weekly_Rate FLOAT,
No_Of_Months INT NOT NULL,
PRIMARY KEY (W_Name,No_Of_Months),
FOREIGN KEY (W_Name) REFERENCES NEWSPAPER(N_Name)
ON DELETE CASCADE	ON UPDATE CASCADE
);

CREATE TABLE MAGAZINE_PRICING (
M_Name varchar(100) NOT NULL,
M_Rate FLOAT,
No_Of_Issues INT NOT NULL,
PRIMARY KEY (M_Name,No_Of_Issues),
FOREIGN KEY (M_Name) REFERENCES MAGAZINE(M_Name)
ON DELETE CASCADE	ON UPDATE CASCADE,
CHECK(No_Of_Issues IN (12,24))
);

CREATE TABLE MAGAZINE_SUBSCRIPTION (
    IdNo INT NOT NULL,
    No_Of_Issues INT NOT NULL,
	Start_Date DATE NOT NULL,
    End_Date DATE,
    M_Name varchar(100),
    Price FLOAT,
    PRIMARY KEY (IdNo, M_Name, Start_Date, No_Of_Issues),
    FOREIGN KEY (IdNo) REFERENCES CUSTOMER(IdNo)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (M_Name) REFERENCES MAGAZINE_PRICING(M_Name)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DAILY_NEWS_SUBSCRIPTION (
    IdNo INT NOT NULL,
	Start_Date DATE NOT NULL,
    End_Date DATE,
    D_Name VARCHAR(100),
    No_Of_Days INT NOT NULL,
    Price FLOAT,
    PRIMARY KEY(IdNo, D_Name, Start_Date, No_Of_Days),
    FOREIGN KEY(IdNo) REFERENCES CUSTOMER(IdNo)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(D_Name) REFERENCES DAILY_NEWS_PRICING(D_Name)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- Weekly News Subscription Table
CREATE TABLE WEEKLY_NEWS_SUBSCRIPTION (
    IdNo INT NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE,
    W_Name VARCHAR(100),
    No_Of_Months INT NOT NULL,
    Price FLOAT,
    PRIMARY KEY(IdNo, W_Name, Start_Date, No_Of_Months),
    FOREIGN KEY(IdNo) REFERENCES CUSTOMER(IdNo)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(W_Name) REFERENCES WEEKLY_NEWS_PRICING(W_Name)
    ON DELETE CASCADE ON UPDATE CASCADE
);  
  